version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: test_pswd
    ports:
      - "5432:5432"