CREATE TABLE IF NOT EXISTS ALBUM(
    ID SERIAL PRIMARY KEY,
    NAME varchar(128) NOT NULL,
    GENRE varchar(256),
    ARTIST_ID INTEGER NOT NULL,
    CONSTRAINT ARTIST_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST (ID)
);

CREATE TABLE IF NOT EXISTS ARTIST(
    ID SERIAL PRIMARY KEY,
    NAME varchar(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPOSITION(
    ID SERIAL PRIMARY KEY,
    NAME varchar(128) NOT NULL,
    DURATION TIME NOT NULL,
    ALBUM_ID INTEGER NOT NULL,
    CONSTRAINT ALBUM_ID_FK FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID)
);

-- CREATE TABLE IF NOT EXISTS ALBUM_COMPOSITION(
--     ALBUM_ID INTEGER REFERENCES ALBUM (ID) ON UPDATE CASCADE ON DELETE CASCADE,
--     COMPOSITION_ID INTEGER REFERENCES COMPOSITIONO (ID) UPDATE CASCADE,
--     CONSTRAINT ARTIST_COMPOSITION_PK PRIMARY KEY (ALBUM_ID, COMPOSITION_ID)
-- );

INSERT INTO  ARTIST(NAME)
VALUES ('M. Jackson')